services:
  ride-app:
    build: .
    container_name: ride-service
    command: >
      sh -c "python manage.py makemigrations --noinput &&
         python manage.py migrate &&
         python manage.py collectstatic --noinput &&
         python core/consumer.py &
         uvicorn ride_service.asgi:application --host 0.0.0.0 --port 8000"
    expose:
      - "8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-user:9092
      - ALLOWED_HOSTS=*
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    networks:
      - raijmobi-network

networks:
  raijmobi-network:
    external: true

volumes:
  media_volume:
  static_volume: