# Generated by Django 5.2.14 on 2026-05-12 00:16

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('expected_arrival', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('available_seats', models.IntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('em_andamento', 'Em Andamento'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='created_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='updated_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('requested_seats', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=50)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.ride')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='created_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Created by')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.userclient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='updated_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('vermelho', 'Vermelho'), ('laranja', 'Laranja'), ('amarelo', 'Amarelo'), ('verde', 'Verde'), ('azul', 'Azul'), ('anil', 'Anil'), ('violeta', 'Violeta'), ('rosa', 'Rosa'), ('preto', 'Preto'), ('branco', 'Branco'), ('cinza', 'Cinza'), ('prata', 'Prata'), ('marrom', 'Marrom'), ('bege', 'Bege')], max_length=50)),
                ('plate', models.CharField(max_length=10)),
                ('seats', models.IntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='created_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='updated_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='core.userclient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caronas', to='core.vehicle'),
        ),
    ]
