# Generated by Django 5.2.14 on 2026-06-05 17:47

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('easyaudit', '0004_auto_20170620_1354_squashed_0019_alter_crudevent_changed_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('is_driver', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Auditoria de Reserva',
                'verbose_name_plural': 'Auditorias de Reservas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('easyaudit.crudevent',),
        ),
        migrations.CreateModel(
            name='RideAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Auditoria de Carona',
                'verbose_name_plural': 'Auditorias de Caronas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('easyaudit.crudevent',),
        ),
        migrations.CreateModel(
            name='UserClientAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Auditoria de UserClient',
                'verbose_name_plural': 'Auditorias de UserClient',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('easyaudit.crudevent',),
        ),
        migrations.CreateModel(
            name='VehicleAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Auditoria de Veículo',
                'verbose_name_plural': 'Auditorias de Veículos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('easyaudit.crudevent',),
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('expected_arrival', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('available_seats', models.IntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('em_andamento', 'Em Andamento'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='created_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='updated_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('requested_seats', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=50)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.ride')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='created_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Created by')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.userclient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='updated_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('model', models.CharField(max_length=100)),
                ('type_vehicle', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto')], max_length=20)),
                ('color', models.CharField(choices=[('vermelho', 'Vermelho'), ('laranja', 'Laranja'), ('amarelo', 'Amarelo'), ('verde', 'Verde'), ('azul', 'Azul'), ('anil', 'Anil'), ('violeta', 'Violeta'), ('rosa', 'Rosa'), ('preto', 'Preto'), ('branco', 'Branco'), ('cinza', 'Cinza'), ('prata', 'Prata'), ('marrom', 'Marrom'), ('bege', 'Bege')], max_length=50)),
                ('plate', models.CharField(max_length=10)),
                ('seats', models.IntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='created_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='updated_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='core.userclient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caronas', to='core.vehicle'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.reservation')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='created_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Created by')),
                ('evaluated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='core.userclient')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='core.userclient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='updated_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Updated by')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reservation', 'evaluator'), name='unique_rating_per_reservation')],
            },
        ),
    ]
