# Generated by Django 6.0.4 on 2026-05-07 19:12

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('seats', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='created_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='updated_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='created_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Created by')),
                ('passenger', models.ManyToManyField(related_name='reservations', to='core.userclient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='updated_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Updated by')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.ride')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('plate', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='created_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='updated_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='core.userclient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caronas', to='core.vehicle'),
        ),
    ]
