# Generated by Django 5.2.14 on 2026-05-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('easyaudit', '0004_auto_20170620_1354_squashed_0019_alter_crudevent_changed_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Auditoria de Reserva',
                'verbose_name_plural': 'Auditorias de Reservas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('easyaudit.crudevent',),
        ),
        migrations.CreateModel(
            name='RideAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Auditoria de Carona',
                'verbose_name_plural': 'Auditorias de Caronas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('easyaudit.crudevent',),
        ),
        migrations.CreateModel(
            name='UserClientAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Auditoria de UserClient',
                'verbose_name_plural': 'Auditorias de UserClient',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('easyaudit.crudevent',),
        ),
        migrations.CreateModel(
            name='VehicleAudit',
            fields=[
            ],
            options={
                'verbose_name': 'Auditoria de Veículo',
                'verbose_name_plural': 'Auditorias de Veículos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('easyaudit.crudevent',),
        ),
        migrations.RemoveField(
            model_name='userclient',
            name='nome',
        ),
        migrations.AddField(
            model_name='userclient',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userclient',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
