# Generated by Django 5.2.14 on 2026-06-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='userclient',
            name='average_rating_update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
