# Generated by Django 5.2.14 on 2026-05-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservationaudit_rideaudit_userclientaudit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type_vehicle',
            field=models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto')], default='carro', max_length=20),
            preserve_default=False,
        ),
    ]
