# Generated by Django 5.2.14 on 2026-06-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userclient_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='suspension_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userclient',
            name='warnig_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
