# Generated by Django 6.0.4 on 2026-05-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ride_reservation_vehicle_ride_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(choices=[('vermelho', 'Vermelho'), ('laranja', 'Laranja'), ('amarelo', 'Amarelo'), ('verde', 'Verde'), ('azul', 'Azul'), ('anil', 'Anil'), ('violeta', 'Violeta'), ('rosa', 'Rosa'), ('preto', 'Preto'), ('branco', 'Branco'), ('cinza', 'Cinza'), ('prata', 'Prata'), ('marrom', 'Marrom'), ('bege', 'Bege')], max_length=50),
        ),
    ]
