# Generated by Django 6.0.4 on 2026-05-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vehicle_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='departure_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
