# Generated by Django 5.2.14 on 2026-06-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userclient_suspension_until_userclient_warnig_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclient',
            old_name='warnig_count',
            new_name='warning_count',
        ),
    ]
