# Generated by Django 5.2.14 on 2026-06-05 16:55

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vehicle_type_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('coment', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='created_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Created by')),
                ('evaluated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_received', to='core.userclient')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='core.userclient')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.reservation')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='updated_%(app_label)s_%(class)s_set', to='core.userclient', verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
