# Generated by Django 6.0.4 on 2026-05-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_seats_ride_avalaibe_seats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='available_seats',
            new_name='avalaible_seats',
        ),
    ]
