# Generated by Django 5.2.14 on 2026-06-15 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
