# Generated by Django 6.0.4 on 2026-05-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_available_seats_ride_avalaible_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='avalaible_seats',
            new_name='available_seats',
        ),
    ]
