# Generated by Django 5.2.14 on 2026-06-21 15:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationaudit',
            options={'verbose_name': 'Auditoria reserva', 'verbose_name_plural': 'Auditorias reservas'},
        ),
        migrations.AlterModelOptions(
            name='rideaudit',
            options={'verbose_name': 'Auditoria carona', 'verbose_name_plural': 'Auditorias caronas'},
        ),
        migrations.AlterModelOptions(
            name='userclientaudit',
            options={'verbose_name': 'Auditoria usuário', 'verbose_name_plural': 'Auditorias usuários'},
        ),
        migrations.AlterModelOptions(
            name='vehicleaudit',
            options={'verbose_name': 'Auditoria veículo', 'verbose_name_plural': 'Auditorias veículos'},
        ),
        migrations.RemoveField(
            model_name='ride',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='created_%(class)s', to='core.userclient'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='updated_%(class)s', to='core.userclient'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='created_%(class)s', to='core.userclient'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='updated_%(class)s', to='core.userclient'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='created_%(class)s', to='core.userclient'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('em_andamento', 'Em andamento'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ride',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='updated_%(class)s', to='core.userclient'),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(choices=[('preto', 'Preto'), ('branco', 'Branco'), ('vermelho', 'Vermelho'), ('azul', 'Azul')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='created_%(class)s', to='core.userclient'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(core.models.get_sentinel_user_client), related_name='updated_%(class)s', to='core.userclient'),
        ),
    ]
