# Generated by Django 6.0.4 on 2026-05-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caronas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carona',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('todos', 'Todos')], default='todos', max_length=20),
        ),
        migrations.AddField(
            model_name='carona',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
